// login
export enum LoginActions {
    LOGIN = 'LOGIN',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILURE = 'LOGIN_FAILURE',
    LOG_OUT = 'LOGOUT'
}
// export const LOGIN: any = 'LOGIN'
// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// export const LOGIN_FAILURE = 'LOGIN_FAILURE';
// export const LOG_OUT = 'LOGOUT'

// export const GET_USER = 'GET_USER';
// export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
// export const GET_USER_FAILURE = 'GET_USER_FAILURE';

//forecast
// export const GET_SETTINGS = 'GET_SETTINGS'
// export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS'
// export const GET_SETTINGS_FAILURE = 'GET_SETTINGS_FAILURE'
// export const UPDATE_SETTINGS = 'UPDATE_SETTINGS'

// export const UPDATE_SETTINGS_NAME = 'UPDATE_SETTINGS_NAME'
// export const UPDATE_SETTINGS_AGE = 'UPDATE_SETTINGS_AGE'
// export const UPDATE_SETTINGS_AMOUNT_FORECAST_DAYS = 'UPDATE_SETTINGS_AMOUNT_FORECAST_DAYS'
// export const UPDATE_SETTINGS_WEATHER_RATE = 'UPDATE_SETTINGS_WEATHER_RATE'
// export const UPDATE_SETTINGS_TEMPERATURE_SCALE = 'UPDATE_SETTINGS_TEMPERATURE_SCALE'